import "./globals.css";
import { Lato } from "next/font/google";
import Link from "next/link";

const monseratt = Lato({ weight: ["400", "700"], subsets: ["latin"] });

export const metadata = {
  title: "Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={monseratt.className}>
        <nav>
          <Link href={"/"}>Home</Link>
          <Link href={"/about"}>About</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
