import "./globals.css";
import Link from "next/link";

export const metadata = {
  title: "Main",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-[#04211d]">
        <nav className="text-center text-2xl text-white space-x-8 border-b-white border-b-2 shadow-white py-2 mb-8 shadow-md">
          <Link href={"/"}>Home</Link>
          <Link href={"/blog"}>Blog</Link>
          <Link href={"/projects"}>Projects</Link>
          <Link href={"/about"}>About</Link>
        </nav>
        <main className="text-xl m-5">{children}</main>
      </body>
    </html>
  );
}
